#+OPTIONS: toc:nil timestamp:nil num:nil postamble:nil
#+TITLE: Curriculum Vitae
#+AUTHOR: Guillaume Buisson
#+EXPORT_EXCLUDE_TAGS: detail

#+BIND: org-export-html-auto-postamble nil
#+BIND: org-export-html-auto-preamble nil
#+BIND: org-export-html-preamble "<h1 class='title'>Curriculum Vitae</h1><h3 class='author'>Guillaume Buisson</h3>"
#+BIND: org-export-html-style-include-default nil

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="stylesheet.css" />

* Technologies
** Languages

Clojure, ClojureScript, Lisp, Javascript, Python, Java, Bash, SQL, HTML, CSS
** Other technology

Onyx, Mesos, Marathon, NixOS, GuixSD, Druid, CouchDB, ElasticSearch, Kibana, Riemann, AWS, Docker, docker-compose, Kafka, Zookeeper, Linux, NixOS, Git, Maven, Leiningen, Apache, Nginx, MongoDB, PostgreSQL, Redis, React, EC2, S3, Emacs, org mode, Travis, OAuth2, OIDC, Bamboo, Jenkins
** Languages

English, French, Spanish
** Interests

Traveling, Home Theater, Home Automation, Functional Programming, Stream Computing, Ant Farming
* Talks
** Fullstack Real time social media analytics with Clojure

Given at ClojureX, London, Dec 2015, The talk was about
leveraging Clojure to build a pipeline analyzing the twitter firehose API,
including sentiment analysis and real time metrics.
** Onyx: Stream computing for the Cloud

Given at Lambda Riviera, Sophia Antipolis, March 2018, I demonstrated the Onyx stream computing
library working with the Twitter Streaming API.
* Experience
** Technical Leader: Cisco [2016 - Present]

Cisco is the number one IT company in the world,

as customers are quickly migrating to cloud offerings,
a goal of the company is to rapidly move the business from hardware to software and recurring revenues.

My team is part of the Security Business Group division (SBG),

working on Advanced Threat Response and Advanced Malware Protection.

I am currently leading a distributed team dedicated to the backend services for both SecureX and Cisco Threat Response.

our mission is to build an Incident Response Orchestration Hub that integrates all the Cisco Security Product features into a single API.

for that purpose we are building a platform including:

- an OAuth2 and OpenID Connect server providing unified login experiences
- an open source Threat Intelligence API Server (CTIA) meant to easily share data using the Cisco Threat Intelligence Model (CTIM)
- a translation layer proxifying and translating all security product APIs and devices data on request
- Many integration modules for all Cisco Security Products
- Many API and data services to feed the product features
- A stream processing pipeline that ingests incoming Incident data to provide automated data enrichments and custom hooks

Techs: Clojure, Clojurescript, Compojure API, ElasticSearch, Kibana, Redis, PostgreSQL, Kafka, Onyx, OAuth2, OIDC.
** Fullstack Clojure Developer: Vigiglobe [2013 - 2016]

Vigiglobe is a startup dedicated to real time social media analytics, working with major social media networks to provide statistics and insights
on any set of conversation topic in real time.

At Vigiglobe I was in charge of the design and the code of the whole platform architecture:
- A scalable stream processing application
- A full API platform serving real time social media analytics
- A single page web application dashboard to display the data
- Multiple data enrichment modules including Sentiment analysis, tokenization and gender detection
- A recurring billing and entitlements system

in this position I was also in charge of:
- Hiring interviews and tests
- Building custom integrations for customers including: Kantar, Skynews, TNS and Twitter.
- Performance benchmarks, tests and continuous delivery.

Techs: Clojure/Clojurescript, Javascript, Node.js, Reagent, Compojure API,
Websockets, Amazonica, Kafka, Zookeeper, Mesos, Marathon, Druid, Hystrix, Redis, MongoDB,
AngularJS , Docker, Twitter Streaming API, Gnip, Facebook Public Feed, Instagram API, some bits of Haskell
** R&D Software Engineer: Dolby Laboratories. [2011 - 2013]

At Dolby Laboratories we invented new experiences for moviegoers like
reinventing the movie theater lobby experience, gamifying preshows and overhauling digital signage.

My job was mostly focused on building the data platform for all these experiences:
- Created a Gaming data platform & APIS
- Developed a Production Network operating center tracking devices
- Worked on an Integration Network operating center for device maintenance
- Created/Directed Gaming Mobile Web apps
- leveraged system administration ticketing/inventory tools

Techs: Javascript, Python, Node.js, Redis, MongoDB, CouchDB, BigCouch, Perl, Zabbix, Proxmox,
Sencha Extjs, Sencha touch, Mysql, PostgreSQL, Spagobi, Websockets
** Software Developer: Orange Portal [2011]

Orange is the top french ISP, its portal serves billions of requests each day, our goal was to make it attractive.

I started being in charge of the code for their new Finance portal.

I then pursued working on a new unified account platform & its APIS.

Finally I participated working on many small advertising operations.
** Technical Project Manager: L'Express.fr [2010-2011]

L'Express.fr is a major news website in France, it is a main source for Live news and Politics.

I was in charge of the whole News website L'Express.fr:
- Working on adding/enhancing backend features
- Worked on some frontend integrations, marketing campaigns
- Technical advisor for L’Express Emploi (Job board)

My main achievement was to migrate the website from a Microsoft stack to a LAMP stack based on the Symfony framework.

Techs: Symfony, XML/XSLT, Talend, Microsoft SQL Server, Mysql
** R&D Web Developer: Figaro Classifieds [2008-2010]

Figaro Classifieds is a a subcompany of Le Figaro french news,

it was created from the merge/aquisitions of many post dot com era classifieds websites including Cadremploi.fr, Explorimmo.com and Keljob.com.


My work involved running experiments merging data from different classified universes, building new websites & experiences.

in this position I built some R&D experiments:
- Immobilier.com, emploi.com, kelformation
- A unified job candidate sourcing tool

I was also in charge of enhancing the internal tools including a media planning platform and a task tracker.

techs included: Symfony, Talend, Java, Oracle DB
** Web Developer: Linagora [2008]

Linagora is one of the main open source editors in France, supplying
open source alternatives for enterprise software.

My tasks involved supporting various projects of the company including:
- Websites creation for government entities
- Developing automated deployments for Alfresco

Techs: Symfony, EZPublish, Javascript, Alfresco, Rhino, Fedora, Debian
** Lead Developer: IAC Inter Action Consultants [2007]

IAC is a company providing software and services around Finance and Cost Optimization.

I worked on building the next flagship tool of their portfolio, Easybench which is a cost comparison/optimization
tool for the industry

Tools included: Symfony and Extjs
** Software Developer: Clever Age [2007]

Clever Age is a company providing services and tools around software engineering

I worked on many customer projects including a news portal for seniors (mageneration.com),
and the revamp of the online store for a major French beauty group (LVMH Dior.com)

Tools included: Symfony, EZPublish, Java
** Web Developer Intern: Big Success [2004-2007]

Big Success is a network of small advertising companies targeting TV, press and social networks

My work was about building a network of websites consolidating the brand, SEO optimizations and System Administration

Tools included: Mambo!, PHP, Symfony, Debian Linux
* Education
** IESA (Campus Edition Numerique)
- Specialiste en bien de communication 2007
** ETS/IRIS
- Computer Science Degree 2004